version: 0.0
os: linux
files:
  - source: dist/
    destination: /usr/share/nginx/html

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: build_react.sh
      timeout: 300
      runas: root
